config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  resources :lists
  resources :tasks
  resources :items
end

app/models/item.rb
class Item < ActiveRecord::Base


end

app/models/list.rb
class List < ActiveRecord::Base

end

app/models/task.rb
class Task < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @item = Item.new

    if params[:filter] == 'groceries'
       @items = Item.all.where(groceries:"true")
    elsif params[:filter] == 'home_improvement'
       @items = Item.all.where(home_improvement:"true")
    elsif params[:filter] == 'electronics'
       @items = Item.all.where(electronics:"true")
    elsif params[:filter] == 'clothes'
       @items = Item.all.where(clothes:"true")
    else
       @items = Item.all

    end
  end

  def new
    @items = Item.all
  end

  def create
    @item = Item.new(params.require(:item).permit(
    :name,
    :kind,
    :groceries,
    :home_improvement,
    :electronics,
    :clothes))
    @item.save
    redirect_to items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(params.require(:item).permit(
    :name,
    :kind,
    :groceries,
    :home_improvement,
    :electronics,
    :clothes))
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    list_params = params.require(:list).permit(:name, :type)
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list_params = params.require(:list).permit(:name, :type)
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to lists_path
  end

def destroy
  @list = List.find(params[:id])
  @list.destroy
  redirect_to lists_path
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    task_params = params.require(:task).permit(:name, :type)
    @task = Task.new
    @task.save
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task_params = params.require(:task).permit(:name, :type)
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :kind %>
  <%= f.text_field :kind %>

  <%= f.submit %>

<% end %>

app/views/items/edit.html.erb
<div class="page-header">
  <h2>EDITING ITEMS!</h2>
</div>
<br><br><br>

<%= form_for @item do |f| %>

  <%= f.text_field :name, class:"col-md-8" %>

  <%= f.check_box :groceries %>
  Groc

  <%= f.check_box :home_improvement %>
  H_Impr

  <%= f.check_box :electronics %>
  Elctr

  <%= f.check_box :clothes %>
  Clths

  <%= f.submit class:"btn btn-primary pull-right" %>
<% end %>








<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div>
  <h2>Items</h2>
</div>

  <%= link_to_if params[:filter], "All Items", items_path %> |
  <%= link_to_if params[:filter] != 'groceries', "Groceries", items_path(filter:"groceries") %> |
  <%= link_to_if params[:filter] != 'home_improvement', "Home Improvement", items_path(filter:"home_improvement") %> |
  <%= link_to_if params[:filter] != 'electronics', "Electronics", items_path(filter:"electronics") %> |
  <%= link_to_if params[:filter] != 'clothes', "Clothes", items_path(filter:"clothes") %> |




<table class="table">
  <tbody>
    <th width="200px">Name</th><th>groc</th><th >h.imp</th><th>elct</th><th>clths</th><th></th><th></th><th></th><th></th>
    <tr>
      <th colspan ="12">
      <%= form_for @item do |f| %>

        <%= f.text_field :name, class:"col-md-8" %>
        &nbsp;&nbsp;&nbsp;&nbsp;

        <%= f.check_box :groceries %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <%= f.check_box :home_improvement %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <%= f.check_box :electronics %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <%= f.check_box :clothes %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <%= f.submit class:"btn btn-primary pull-right" %>

      <% end %>
    </th>
    </tr>

      <% @items.each do |item| %>

        <tr>

          <td class="col-md-8"><%= item.name %></td>
          <td><%= item.groceries %></td>
          <td><%= item.home_improvement %></td>
          <td><%= item.electronics %></td>
          <td><%= item.clothes %></td>
          <td></td>
          <td><%= link_to "Edit", edit_item_path(item), class:"btn btn-warning pull-right" %><td>
          <td><%= link_to "Delete", item, class:"btn btn-danger pull-right", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

      <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<div class="page-header">
  <h2>dude, NEW items!</h2>
</div>
<br><br><br>



<%= form_for @item do |f| %>

  <%= f.text_field :name, class:"col-md-8" %>

  <%= f.check_box :groceries %>
  Groc

  <%= f.check_box :home_improvement %>
  H_Impr

  <%= f.check_box :electronics %>
  Elctr

  <%= f.check_box :clothes %>
  Clths

  <%= f.submit class:"btn btn-primary pull-right" %>

<% end %>




<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h2>Item Details</h2>

<table class="table" width="100%">
      <tr>
<% if notice.is_a? String %>

<div class="text-center alert alert-info"><%= notice %></div>
<% end %>


        <tr><td width="100%" class="pull-left"><strong>Name: </strong><%= @item.name %></td></tr>
        <tr><td width="100%" class="pull-left"><strong>Groceries: </strong><%= @item.groceries %></td></tr>
      </tr>
</table>







<%= link_to "Edit", edit_item_path(@item) %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tada</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="navbar">
  <div class="container">
    <!-- navbar here -->
  </div>
</div>
<div class="container">






  <%= yield %>
</div>
<footer>
  <div class="container">
    <!-- footer stuff here -->
  </div>
</footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


</body>
</html>

app/views/lists/_fomr.html.erb
form page

app/views/lists/edit.html.erb
<div class="page-header">
  <h2>EDITING LISTS!</h2>
</div>
<br><br><br>

<%= form_for @list do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.submit %>

<% end %>


<%= link_to "Delete This Thing!", list_path(@list), :method => :delete%>

app/views/lists/index.html.erb
<div class="page-header">
  <h2>Lists Index</h2>
</div>

<br><br><br>
<%= link_to "Add a List", new_list_path %>


<table>
<% @lists.each do |list| %>
  <tr>
    <td><%= list.name %></td>
    <td><%= list.type %></td>
    <td><%= link_to "Edit", edit_list_path(list) %><td>
    <td><%= link_to "Delete", list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>
</table>

app/views/lists/new.html.erb
<div class="page-header">
  <h2>dude, NEW lists!</h2>
</div>
<br><br><br>

<%= form_for @list do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.submit %>

<% end %>

app/views/lists/show.html.erb
<div class="page-header">
  <h2>show page</h2>
</div>





<h2><%= link_to @list.name %></h2>








<%= link_to "Edit", edit_list_path(@list), class:"btn btn-info col-md-offset-1"  %>

<%= link_to "Destroy", list_path(@list), class:"btn btn-danger", :method => :delete%>

app/views/pages/index.html.erb
<p>This is my personal project!</p>

<%= link_to "lists", lists_path %>


<%= link_to "items", items_path %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h2>EDITING TASKS!</h2>
</div>
<br><br><br>

<%= form_for @task do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.submit %>

<% end %>

app/views/tasks/index.html.erb
this is my tasks index

<%= link_to "Add a Task", new_task_path %>








<tbody>
    <th>Name</th><th width="100px", class="text-center">Type</th><th></th><th></th><th></th><th></th>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, task.name %></td>
        <td><%= task.type %></td>
        <td width="30px"><%= link_to 'Show', task, class: "pull-right btn btn-success" %></td>
        <td width="30px"><%= link_to 'Edit', edit_task_path(task), class: "pull-right btn btn-info" %></td>
        <td width="30px"><%= link_to 'Destroy', task, class: "pull-right btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :type %>
  <%= f.text_field :type %>

  <%= f.submit %>

<% end %>